config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'carts/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :products

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    post 'checkout', to: 'carts#checkout'
  end

  resources :orders, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  
  enum payment: {boleto: 0, credito: 1}
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  delegate :name, to: :product, prefix: true
  delegate :photo, to: :product, prefix: true
end

app/models/product.rb
class Product < ApplicationRecord
  
  mount_uploader :photo, PhotoUploader

  validates :price, :name, :photo, presence: true

  def cart_action(current_user_id)
    if $redis.sismember "cart#{current_user_id}", id
      "Remove from"
    else
      "Add to"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def cart_count
    $redis.scard "cart#{id}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def show
    cart_ids = $redis.smembers current_user_cart
    @cart = Product.find(cart_ids)
  end

  def add
    $redis.sadd current_user_cart, params[:product_id]
    render json: current_user.cart_count, status: 200
  end

  def remove
    $redis.srem current_user_cart, params[:product_id]
    render json: current_user.cart_count, status: 200
  end

  def checkout
    CheckoutService.create(params, current_user)
    $redis.del current_user_cart
    render json: current_user.cart_count, status: 200
  end

  private

  def current_user_cart
    "cart#{current_user.id}"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.where(user_id: current_user.id)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end


  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = 'Produto cadastrado com sucesso.'
      return redirect_to root_path
    end
    render :new
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :photo, :quantity)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def esgotado?(produto)
    produto.quantity.zero?
  end

  def esta_no_carrinho?(produto)
    $redis.sismember "cart#{current_user.id}", produto.id
  end
end

app/views/carts/show.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4>Meu Carrinho</h4>
    <p class="mb0"> Você tem <span class="cart-count"><%=current_user.cart_count%></span> items no seu carrinho</p>
  </div>

  <div id="checkout-processing" class="checkout-modal bg-white border border-primary flex-column justify-content-center align-items-center">
      <p class="display-5">Estamos processando seu pedido...</p>
     <%= link_to "Desfazer Pedido", '#', class:'btn btn-warning text-ligth', id:'undo-checkout' %>
  </div>

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Preço</th>
        <th scope="col">Ação</th>
      </tr>
    </thead>
    <tbody>
      <% @cart.each do |product| %>

      <tr>
        <td>
          <%=link_to product do%>
            <%=image_tag product.photo.thumb.url, class: "radius-l1"%>
          <%end%>
        </td>
        <td><%= product.name %></td>
        <td>R$ <%= product.price %></td>
        <td>
          <%=link_to '' , class:"cart-button btn btn-outline-danger", data: {target: remove_from_cart_path(product)} do%>
            <%= fa_icon "times" %>
          <%end%>
        </td>
      </tr>
  <%end%>
      </tbody>
  </table>

  <hr>

  <div class="row">
    <div class="col">
    <p class="h5">Forma de Pagamento</p>
      <div class="custom-control custom-radio">
        <input type="radio" id="customRadio1" name="payment" value=0 class="custom-control-input" checked>
        <label class="custom-control-label" for="customRadio1">Boleto</label>
      </div>
      <div class="custom-control custom-radio">
        <input type="radio" id="customRadio2" name="payment" value=1 class="custom-control-input">
        <label class="custom-control-label" for="customRadio2">Cartão</label>
      </div>
    </div>
  </div>

  <div class="row text-right">
    <div class="col">
      <%= link_to '', class:'btn btn-primary text-ligth', id:'checkout',  data: {url: checkout_cart_path(cart: @cart)} do %>
        <%= fa_icon "arrow-circle-right" %>
        Finalizar Pedido
      <%end%>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4 text-primary">Pixel Store</h1>
  <p class="lead text-muted">Este sistema é apenas um protótipo utilizado no desafio 1 do treinamento de liderança técnica da STI.</p>
</div>


<div class="card-deck mb-3 text-center">
<% @products.each do |product| %>
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 text-light font-weight-normal"><%= product.name %></h4>
          </div>

          <div class="card-body">
            <% if product.photo.present? %>
                <%= image_tag product.photo.medium.url, class: 'rounded border border-gray imagem-lista-products'  %>
            <% else %>
                <%= image_tag "no-picture.png", class: 'rounded border border-gray imagem-lista-products' %>
            <% end %>
            <p class="media-body pb-3 mb-0 lh-125 pr-5">
              <strong class="d-block text-gray-dark"></strong>
            </p>
            <h2 class="card-title text-info pricing-card-title">R$ <%= product.price %></h2>
            <% if esgotado?(product) %>
              <p class="d-block mb-2 text-danger">ESGOTADO</p>    
            <% else %>
              <small class="d-block mb-2 text-muted"><%= product.quantity %> unidades disponíveis</small>
              <%= link_to 'Ver', product_path(product), class: 'btn btn-outline-primary' %>
            <% end %>
          </div>
        </div>

        <% end %>

        
      </div>

      <%= javascript_include_tag "cart.js" %>

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 text-center">
            <%=image_tag 'heart.png', class: "mb-2", size:"36x36" %>         
            <small class="d-block mb-3 text-muted">Romulo Mourão © 2018</small>
          </div>
        </div>
    
</footer>

app/views/layouts/_navbar.html.erb
   <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal"><%= link_to "PIXEL STORE", root_path %></h5>
      <nav class="my-2 my-md-0 mr-md-3">
      <% if user_signed_in? %>
      <%= link_to 'Meus Pedidos', orders_path %>  
      <%= link_to cart_path, class:"btn btn-outline-primary" do %>
        <%= fa_icon "shopping-cart 2x" %> 
        <span class="cart-count"><%=current_user.cart_count%></span>
        <% end %>
        
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-outline-primary') %>        
        
      <% else %>
       
        <%= link_to('Login', new_user_session_path, class: 'btn btn-sm btn-outline-primary')  %>  
       
      <% end %>
      </nav>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StiDesafio1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=VT323' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    <%= render 'layouts/footer'%>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h3>Meus Pedidos</h3>
  </div>

      <% @orders.each do |order| %>

      <div class="card mb-4 box-shadow">
        <div class="card-header text-white">
          <p class="h5">Pedido #<%= order.id %>
            <span class="small">Realizado em <%= l order.created_at, format: :short %></span>
          </p>
         <p>Forma de Pagamento:  <%= order.payment %></p>
        </div>

       <div class="card-body">
       
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Item</th>
              <th scope="col">Preço</th>
            </tr>
          </thead>

          <tbody>
        <% order.order_items.each do |item| %>
            <tr>
              <td><%=image_tag item.product_photo.thumb.url, class: "radius-l1"%></td>
              <td><%= item.product_name %></td>
              <td><%= item.price %></td>
            </tr>
        <%end%>
          </tbody>
  </table>
  </div>
  </div>
          
      <%end%>




</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |f| %>
    <% if product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, 'Nome:' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :price, 'Preço: ' %>
      <%= f.text_field :price, class: 'form-control' %>
    </div>

    <div class="form-group">
      <div class="field">
        <%= f.label :photo, 'Foto do Produto:' %> <br/>
        <%= f.file_field :photo %>
      </div>
    </div>

    <div class="form-group">
      <div class="field">
        <%= f.label :quantity, 'Quantidade:' %> <br/>
        <%= f.number_field :quantity %>
      </div>
    </div>

    <div class="row">
        <%= f.submit 'Salvar', class: 'btn btn-success pull-right' %>
    </div>
<% end %>

app/views/products/index.html.erb
<% @products.each do |product| %>
        <div class="card p-3 mb-3">
          <div class="row">
            <div class="col-md-6">
              <div class="media align-items-center text-muted py-3 px-3">
                <% if product.photo.present? %>
                    <%= image_tag product.photo.medium.url, class: 'mr-4 rounded border border-gray imagem-lista-products'  %>
                <% else %>
                    <%= image_tag "no-picture.png", class: 'mr-4 rounded border border-gray imagem-lista-products' %>
                <% end %>
                <p class="media-body pb-3 mb-0 lh-125 pr-5">
                  <strong class="d-block text-gray-dark"><%= product.name %></strong>
                  <span class="d-block pb-2 small">R$ <%= product.price %></span>
                </p>
              </div>
            </div>
          </div>
        </div>
    <% end %>

app/views/products/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="">
      <% if @product.photo.present? %>
      <%= image_tag @product.photo.big.url, class: 'col rounded border border-gray imagem-lista-@products'  %>
      <% else %>
      <%= image_tag "no-picture.png", class: 'rounded border border-gray imagem-lista-@products' %>
      <% end %>
    </div>
    <div class="col">
      <div class="card box-shadow">

        <div class="card-header">
          <h4 class="my-0 text-light font-weight-normal">
            <%= @product.name %>
          </h4>
        </div>

        <div class="card-body">

          <p class="media-body pb-3 mb-0 lh-125 pr-5">
            <strong class="d-block text-gray-dark"></strong>
          </p>
          <h2 class="card-title text-info pricing-card-title">R$
            <%= @product.price %>
          </h2>
          <% if esgotado?(@product) %>
            <p class="d-block mb-2 text-danger">ESGOTADO</p>
            <% else %>
            <p class="d-block mb-2 text-muted">
              <%= @product.quantity %> unidades disponíveis</p>
            <% if signed_in? and esta_no_carrinho?(@product) %>
              <%= link_to '', class:"cart-button btn btn-outline-danger", data: {target: remove_from_cart_path(@product)} do %>
                <%= fa_icon "times" %>
                <%= fa_icon "shopping-cart 2x" %> Remover do Carrinho
              <%end%>
            <% else %>
               <%= link_to '', class:"cart-button btn btn-outline-primary", data: {target: add_to_cart_path(@product)} do %>
                <%= fa_icon "plus" %>
                <%= fa_icon "shopping-cart 2x" %> Adicionar ao Carrinho
              <%end%>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    
  </div>
</div> 